### ISSUE TITLE
Translate the following pages to Hindi

### ISSUE THREAD

**Issue by karthik1997** [coronasafe/hindi#2]
- [x] Reducing the risk to the team
- [x] Summary
- [x] Pastoral care
- [x] Health advisories by Kerala government
- [x] Official resources
- [x] Control rooms in Kerala
- [x] State and district level organizations

**Comment by ManasJayanth** [comment]
Thanks @karthik1997 I wasn't sure how to handle regional content - do we lookup Hindi speaking states and their respective state government guidelines and merge them or have separate pages for them (incase we find them)?

**Comment by fasalmbt** [comment]
@prometheansacrifice @bodhish 

Rest part of Hindi is also done in this PR.

https://github.com/coronasafe/hindi/pull/15

**Comment by ManasJayanth** [comment]
Thanks, everyone who helped translate the remaining pages!

**Comment by akaushal123** [comment]
@karthik1997 are all pages translated?

**Comment by karthik1997** [comment]
Don't know about Tamil, rest of them are completed

**Comment by akaushal123** [comment]
@karthik1997  OK
