### ISSUE TITLE
भीड़-खट्टा doesn't sound right

### ISSUE THREAD

**Issue by ManasJayanth** [coronasafe/hindi#3]
> कोरोनो वायरस बीमारी में सुरक्षित रहने के लिए एक सत्यापित भीड़-खट्टा गाइड

भीड़-खट्टा is that the correct word?

**Comment by zzat** [comment]
How about: कोरोनो वायरस बीमारी से सुरक्षित रहने के लिए लोगों द्वारा एकत्रित एक सत्यापित गाइड ?

**Comment by ManasJayanth** [comment]
Closed by #7
