### ISSUE TITLE
Review needed: चिकित्सा स्थिति, चिकित्सा हस्तक्षेप

### ISSUE THREAD

**Issue by ManasJayanth** [coronasafe/hindi#4]
> लगभग 80% संक्रमित केवल हल्के लक्षण दिखाते हैं और मानक चिकित्सा ध्यान देते हैं। वृद्ध लोगों और एक अंतर्निहित या पिछली चिकित्सा स्थिति के साथ गंभीर लक्षण विकसित होते हैं और चिकित्सा हस्तक्षेप के बिना घातक साबित हो सकते हैं। अध्ययनों के अनुसार संक्रमित का लगभग 14% गंभीर रूप से बीमार हो जाता है और 5% गंभीर होता है।

Words  चिकित्सा स्थिति, चिकित्सा हस्तक्षेप need to be reviewed. Should this paragraph be reworded?

**Comment by zzat** [comment]
I've reworded it.
> लगभग 80% संक्रमित केवल हल्के लक्षण दिखाते हैं और मानक चिकित्सा से स्वस्थ हो जाते हैं। वृद्ध लोगों और किसी पुरानी बीमारी से ग्रस्त लोगों मे गंभीर लक्षण विकसित हो सकते हैं और चिकित्सा हस्तक्षेप के बिना यह घातक साबित हो सकता है। अध्ययनों के अनुसार संक्रमित लोगो में से लगभग 14% बहुत अधिक बीमार हो जाते हैं और 5% की स्तिथि बहुत गंभीर हो जाती है।

If this looks fine, I'll send a PR.

**Comment by tucosaurus** [comment]
@zzat This looks good to me. Please send a PR.

**Comment by tucosaurus** [comment]
Merged through #21. We should be good to close this one. @prometheansacrifice

**Comment by ManasJayanth** [comment]
Thanks, @tucosaurus
